
# Name  : Nanda Vardhan Reddy
# Redg No: 24040208001






# Basic Operations


#### c() – Create a vector (a list of items)

In [10]:
vec_num2 <- c(10, 20, 30, 40)
print(vec_num2)

vec_char2 <- c("red", "blue", "green")
print(vec_char2)

vec_log2 <- c(FALSE, TRUE, FALSE)
print(vec_log2)

vec_mix2 <- c(5, "world", FALSE)
print(vec_mix2)


[1] 10 20 30 40
[1] "red"   "blue"  "green"
[1] FALSE  TRUE FALSE
[1] "5"     "world" "FALSE"


#### seq() – Generate a sequence of numbers

In [11]:
seq1 <- seq(5, 15)
print(seq1)

seq2 <- seq(2, 20, by = 3)
print(seq2)

seq3 <- seq(10, 50, length.out = 6)
print(seq3)


 [1]  5  6  7  8  9 10 11 12 13 14 15
[1]  2  5  8 11 14 17 20
[1] 10 18 26 34 42 50


#### rep() – Repeat values

In [12]:
rep1 <- rep(c(4, 5, 6), times = 4)
print(rep1)

rep2 <- rep(c(7, 8, 9), each = 2)
print(rep2)

rep3 <- rep(c("X", "Y", "Z"), each = 3, times = 2)
print(rep3)


 [1] 4 5 6 4 5 6 4 5 6 4 5 6
[1] 7 7 8 8 9 9
 [1] "X" "X" "X" "Y" "Y" "Y" "Z" "Z" "Z" "X" "X" "X" "Y" "Y" "Y" "Z" "Z" "Z"


#### length() – Get the number of items in a vector or list

In [13]:
len1 <- length(c(5, 15, 25, 35, 45))
print(len1)

len2 <- length(c("apple", "banana", "cherry", "date", "elderberry"))
print(len2)

my_list <- list(x = 100, y = "hello", z = FALSE, w = 3.14)
print(length(my_list))


[1] 5
[1] 5
[1] 4


#### sort() – Sort values in order

In [14]:
sorted1 <- sort(c(8, 3, 12, 7, 4))
print(sorted1)

sorted2 <- sort(c(15, 6, 22, 9, 1), decreasing = TRUE)
print(sorted2)

sorted3 <- sort(c("grape", "orange", "kiwi", "mango"))
print(sorted3)


[1]  3  4  7  8 12
[1] 22 15  9  6  1
[1] "grape"  "kiwi"   "mango"  "orange"


#### order() – Get the index order that would sort the vector

In [15]:
ord1 <- order(c(30, 10, 50, 20))
print(ord1)

ord2 <- order(c("zebra", "lion", "elephant", "giraffe"))
print(ord2)


[1] 2 4 1 3
[1] 3 4 2 1


#### rev() – Reverse the order of items

In [16]:
rev1 <- rev(c(10, 20, 30, 40, 50))
print(rev1)

rev2 <- rev(c("apple", "banana", "cherry", "date"))
print(rev2)


[1] 50 40 30 20 10
[1] "date"   "cherry" "banana" "apple" 


#### unique() – Get unique items from a vector


In [17]:
uniq1 <- unique(c(10, 20, 20, 30, 30, 40))
print(uniq1)

uniq2 <- unique(c("red", "blue", "red", "green", "blue"))
print(uniq2)


[1] 10 20 30 40
[1] "red"   "blue"  "green"


#### table() – Make a frequency table of items


In [ ]:
# Example 1: Create a table for numbers
tbl1 <- table(c(1, 2, 2, 3, 3, 3))
print(tbl1)

# Example 2: Create a table for fruit names
tbl2 <- table(c("apple", "banana", "apple", "cherry"))
print(tbl2)


1 2 3 
1 2 3 

 apple banana cherry 
     2      1      1 


#### match() – Find the first index of a match

In [ ]:
# Example 1: Find the index of 3 in a vector
match1 <- match(3, c(1, 2, 3, 4, 3))
print(match1)

# Example 2: Find the index of "banana" in a vector
match2 <- match("banana", c("apple", "banana", "cherry"))
print(match2)

[1] 3
[1] 2


#### %in% – Check if items exist in a vector


In [ ]:
# Example 1: Check if number 3 is in a vector
in1 <- 3 %in% c(1, 2, 3, 4)
print(in1)

# Example 2: Check if "apple" and "kiwi" are in a vector
in2 <- c("apple", "kiwi") %in% c("apple", "banana", "cherry")
print(in2)

[1] TRUE
[1]  TRUE FALSE


#### which() – Get indices of elements satisfying a condition


In [ ]:
# Example 1: Find indices where numbers are greater than 3
which1 <- which(c(1, 4, 2, 5, 3) > 3)
print(which1)

# Example 2: Find indices of letters that are "a" in a vector
which2 <- which(c("a", "b", "a", "c") == "a")
print(which2)

[1] 2 4
[1] 1 3


#### any() – Check if any element meets a condition


In [ ]:
# Example 1: Check if any number is greater than 10
any1 <- any(c(1, 5, 8, 12) > 10)
print(any1)

# Example 2: Check if any element is TRUE
any2 <- any(c(FALSE, FALSE, TRUE))
print(any2)

[1] TRUE
[1] TRUE


#### all() – Check if all elements meet a condition


In [ ]:
# Example 1: Check if all numbers are positive
all1 <- all(c(1, 2, 3, 4) > 0)
print(all1)

# Example 2: Check if all numbers are even
all2 <- all(c(2, 4, 6, 8) %% 2 == 0)
print(all2)

[1] TRUE
[1] TRUE


#### is.na() – Check for missing (NA) values


In [ ]:
# Example 1: Find NA in a vector
na_check1 <- is.na(c(1, NA, 3))
print(na_check1)

# Example 2: Check NA in a character vector with NA values
na_check2 <- is.na(c("apple", NA, "banana"))
print(na_check2)

[1] FALSE  TRUE FALSE
[1] FALSE  TRUE FALSE


#### na.omit() – Remove NA values from data

In [ ]:
# Example 1: Remove NA from a numeric vector
clean1 <- na.omit(c(1, NA, 3, NA, 5))
print(clean1)

# Example 2: Remove NA from a data frame
df_na <- data.frame(a = c(1, NA, 3), b = c("x", "y", NA))
clean_df <- na.omit(df_na)
print(clean_df)

[1] 1 3 5
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"
  a b
1 1 x


#### replace() – Replace values in a vector


In [ ]:
# Example 1: Replace all 2's with 99
rep_vec <- c(1, 2, 3, 2, 4)
replaced1 <- replace(rep_vec, rep_vec == 2, 99)
print(replaced1)

# Example 2: Replace the value at position 3 with 0
replaced2 <- replace(rep_vec, 3, 0)
print(replaced2)

[1]  1 99  3 99  4
[1] 1 2 0 2 4


#### paste() – Concatenate strings (with a space by default)


In [ ]:
# Example 1: Paste two words together
str1 <- paste("Hello", "World")
print(str1)

# Example 2: Paste multiple strings
str2 <- paste("This", "is", "a", "sentence.")
print(str2)

# Example 3: Paste with a custom separator and collapse a vector
str3 <- paste(c("R", "is", "fun"), collapse = "-")
print(str3)

[1] "Hello World"
[1] "This is a sentence."
[1] "R-is-fun"


#### paste0() – Concatenate strings with no spaces


In [ ]:
# Example 1: Combine strings without spaces
str4 <- paste0("Hello", "World")
print(str4)

# Example 2: Combine more than two strings
str5 <- paste0("R", "is", "cool")
print(str5)

[1] "HelloWorld"
[1] "Riscool"


#### toupper() – Convert strings to uppercase


In [ ]:
# Example 1: Convert a single string
upper1 <- toupper("hello")
print(upper1)

# Example 2: Convert a vector of strings
upper2 <- toupper(c("apple", "banana"))
print(upper2)

[1] "HELLO"
[1] "APPLE"  "BANANA"


#### tolower() – Convert strings to lowercase


In [ ]:
# Example 1: Convert a single string
lower1 <- tolower("HELLO")
print(lower1)

# Example 2: Convert a vector of strings
lower2 <- tolower(c("APPLE", "BANANA"))
print(lower2)

[1] "hello"
[1] "apple"  "banana"


#### substr() – Extract a part of a string


In [ ]:
# Example 1: Get substring from character 2 to 4
sub1 <- substr("abcdef", 2, 4)
print(sub1)

# Example 2: Get substring from a vector of strings
sub2 <- substr(c("Rprogramming", "statistics"), 1, 3)
print(sub2)

[1] "bcd"
[1] "Rpr" "sta"


#### grep() – Search for pattern and return indices


In [ ]:
# Example 1: Find positions of "a" in a character vector
grep1 <- grep("a", c("apple", "banana", "cherry"))
print(grep1)

# Example 2: Use regex to find words starting with "b"
grep2 <- grep("^b", c("apple", "banana", "blueberry", "cherry"))
print(grep2)

[1] 1 2
[1] 2 3


#### gsub() – Replace pattern in strings

In [ ]:
# Example 1: Replace "a" with "X" in a string
gsub1 <- gsub("a", "X", "banana")
print(gsub1)

# Example 2: Replace digits with "-" in a vector of strings
gsub2 <- gsub("[0-9]", "-", c("a1b2", "3c4d"))
print(gsub2)

[1] "bXnXnX"
[1] "a-b-" "-c-d"


#### strsplit() – Split strings by a delimiter

In [ ]:
# Example 1: Split a sentence by space
split1 <- strsplit("R is fun", " ")
print(split1)

# Example 2: Split a string by a comma
split2 <- strsplit("apple,banana,cherry", ",")
print(split2)


[[1]]
[1] "R"   "is"  "fun"

[[1]]
[1] "apple"  "banana" "cherry"



#### as.numeric() – Convert to numeric type

In [ ]:
# Example 1: Convert a numeric string to number
num1 <- as.numeric("123")
print(num1)

# Example 2: Convert a factor to numeric (first convert to character!)
fact <- factor(c("10", "20", "30"))
num2 <- as.numeric(as.character(fact))
print(num2)

[1] 123
[1] 10 20 30


#### as.character() – Convert to character type

In [ ]:
# Example 1: Convert a number to a string
char1 <- as.character(456)
print(char1)

# Example 2: Convert a factor to a string
fact2 <- factor(c("dog", "cat"))
char2 <- as.character(fact2)
print(char2)

[1] "456"
[1] "dog" "cat"


#### as.factor() – Convert to factor (categorical data)

In [ ]:
# Example 1: Convert a character vector to factor
fact3 <- as.factor(c("red", "green", "red", "blue"))
print(fact3)

# Example 2: Convert a numeric vector to factor
fact4 <- as.factor(c(1, 2, 2, 3))
print(fact4)

[1] red   green red   blue 
Levels: blue green red
[1] 1 2 2 3
Levels: 1 2 3


#### as.Date() – Convert string to Date

In [ ]:
# Example 1: Default conversion (expects yyyy-mm-dd)
date1 <- as.Date("2025-01-01")
print(date1)

# Example 2: Specify a different format (day/month/year)
date2 <- as.Date("01/02/2025", format = "%d/%m/%Y")
print(date2)

[1] "2025-01-01"
[1] "2025-02-01"


#### Sys.Date() – Get the current system date

In [ ]:
# Example 1: Simply print today’s date
today1 <- Sys.Date()
print(today1)

# Example 2: Save today’s date in a variable and show it
today2 <- Sys.Date()
cat("Today is:", today2, "\n")

[1] "2025-02-03"
Today is: 20122 



#  Mathematical & Statistical Functions


#### sum() – Sum of elements


In [ ]:
# Example 1: Sum of numbers in a vector
total1 <- sum(c(1, 2, 3, 4))
print(total1)

# Example 2: Sum of a sequence of numbers
total2 <- sum(1:10)
print(total2)

[1] 10
[1] 55


#### prod() – Product of elements


In [ ]:
# Example 1: Product of numbers in a vector
prod1 <- prod(c(1, 2, 3, 4))
print(prod1)

# Example 2: Product of a sequence
prod2 <- prod(1:5)
print(prod2)

[1] 24
[1] 120


#### cumsum() – Cumulative sum of elements


In [ ]:
# Example 1: Cumulative sum for a vector
cum_sum1 <- cumsum(c(1, 2, 3, 4))
print(cum_sum1)

# Example 2: Cumulative sum with negative numbers
cum_sum2 <- cumsum(c(10, -2, 3, -1))
print(cum_sum2)

[1]  1  3  6 10
[1] 10  8 11 10


#### cumprod() – Cumulative product of elements


In [ ]:
# Example 1: Cumulative product for a vector
cum_prod1 <- cumprod(c(1, 2, 3, 4))
print(cum_prod1)

# Example 2: Cumulative product for a sequence
cum_prod2 <- cumprod(1:5)
print(cum_prod2)


[1]  1  2  6 24
[1]   1   2   6  24 120


#### mean() – Calculate the average


In [ ]:
# Example 1: Mean of a vector
mean1 <- mean(c(10, 20, 30))
print(mean1)

# Example 2: Mean of a column in a data frame
df_mean <- data.frame(x = c(2, 4, 6, 8))
mean2 <- mean(df_mean$x)
print(mean2)

[1] 20
[1] 5


#### median() – Calculate the median (middle value)


In [ ]:
# Example 1: Median of odd-length vector
med1 <- median(c(1, 3, 5))
print(med1)

# Example 2: Median of even-length vector
med2 <- median(c(2, 4, 6, 8))
print(med2)

[1] 3
[1] 5


#### min() – Find the minimum value


In [ ]:
# Example 1: Minimum of a numeric vector
min1 <- min(c(5, 2, 9, 1))
print(min1)

# Example 2: Minimum of another set of numbers
min2 <- min(c(-10, 0, 10))
print(min2)

[1] 1
[1] -10


#### max() – Find the maximum value


In [ ]:
# Example 1: Maximum of a numeric vector
max1 <- max(c(5, 2, 9, 1))
print(max1)

# Example 2: Maximum from a sequence
max2 <- max(1:10)
print(max2)

[1] 9
[1] 10


#### range() – Get the minimum and maximum as a vector


In [ ]:
# Example 1: Range of numbers
range1 <- range(c(5, 2, 9, 1))
print(range1)

# Example 2: Range for a sequence
range2 <- range(10:20)
print(range2)

#### var() – Calculate variance


In [ ]:
# Example 1: Variance of a vector
var1 <- var(c(1, 2, 3, 4, 5))
print(var1)

# Example 2: Variance for another set
var2 <- var(c(10, 15, 10, 20))
print(var2)

[1] 2.5
[1] 22.91667


#### sd() – Standard deviation


In [ ]:
# Example 1: Standard deviation of a vector
sd1 <- sd(c(1, 2, 3, 4, 5))
print(sd1)

# Example 2: Standard deviation of another vector
sd2 <- sd(c(10, 20, 30, 40))
print(sd2)

[1] 1.581139
[1] 12.90994


#### quantile() – Compute quantiles of a vector


In [ ]:
# Example 1: Default quantiles (0%, 25%, 50%, 75%, 100%)
q1 <- quantile(c(1, 2, 3, 4, 5))
print(q1)

# Example 2: Specific quantiles (10% and 90%)
q2 <- quantile(c(1, 2, 3, 4, 5), probs = c(0.1, 0.9))
print(q2)

  0%  25%  50%  75% 100% 
   1    2    3    4    5 
10% 90% 
1.4 4.6 


#### round() – Round numbers to the nearest integer or digit


In [ ]:
# Example 1: Round a single number
round1 <- round(3.14159)
print(round1)

# Example 2: Round numbers in a vector
round2 <- round(c(1.2, 2.5, 3.7))
print(round2)

# Example 3: Round to 2 decimal places
round3 <- round(3.14159, digits = 2)
print(round3)

[1] 3
[1] 1 2 4
[1] 3.14


#### ceiling() – Round numbers up


In [ ]:
# Example 1: Ceiling of a single number
ceil1 <- ceiling(3.1)
print(ceil1)

# Example 2: Ceiling of a vector of numbers
ceil2 <- ceiling(c(1.2, 2.5, 3.7))
print(ceil2)

[1] 4
[1] 2 3 4


#### floor() – Round numbers down


In [ ]:
# Example 1: Floor of a single number
floor1 <- floor(3.9)
print(floor1)

# Example 2: Floor of a vector of numbers
floor2 <- floor(c(1.2, 2.5, 3.7))
print(floor2)

[1] 3
[1] 1 2 3


#### abs() – Absolute value (remove negative sign)


In [ ]:
# Example 1: Absolute value of a negative number
abs1 <- abs(-5)
print(abs1)

# Example 2: Absolute values in a vector
abs2 <- abs(c(-1, -2, 3, -4))
print(abs2)

[1] 5
[1] 1 2 3 4


#### sqrt() – Square root of a number


In [ ]:
# Example 1: Square root of a number
sqrt1 <- sqrt(16)
print(sqrt1)

# Example 2: Square root for each element in a vector
sqrt2 <- sqrt(c(4, 9, 16))
print(sqrt2)

[1] 4
[1] 2 3 4


#### log() – Natural logarithm (base e)


In [ ]:
# Example 1: Logarithm of a number
log1 <- log(10)
print(log1)

# Example 2: Logarithm for a vector of numbers
log2 <- log(c(1, 10, 100))
print(log2)

[1] 2.302585
[1] 0.000000 2.302585 4.605170


#### exp() – Exponential function (e raised to the power)


In [ ]:
# Example 1: Exponential of a number
exp1 <- exp(1)
print(exp1)

# Example 2: Exponential for a vector
exp2 <- exp(c(0, 1, 2))
print(exp2)

[1] 2.718282
[1] 1.000000 2.718282 7.389056


#### factorial() – Factorial of a number (n!)


In [ ]:
# Example 1: Factorial of 5
fact1 <- factorial(5)
print(fact1)

# Example 2: Factorial of 0 (by definition 0! = 1)
fact2 <- factorial(0)
print(fact2)

[1] 120
[1] 1


#### choose() – Binomial coefficient (n choose k)


In [ ]:
# Example 1: How many ways to choose 2 from 5
choose1 <- choose(5, 2)
print(choose1)

# Example 2: Vectorized version (choose for each element)
choose2 <- choose(10, 1:5)
print(choose2)

[1] 10
[1]  10  45 120 210 252


#### sin() – Sine of an angle (in radians)


In [ ]:
# Example 1: Sine of 0
sin1 <- sin(0)
print(sin1)

# Example 2: Sine of pi/2
sin2 <- sin(pi/2)
print(sin2)

[1] 0
[1] 1


#### cos() – Cosine of an angle


In [ ]:
# Example 1: Cosine of 0
cos1 <- cos(0)
print(cos1)

# Example 2: Cosine of pi
cos2 <- cos(pi)
print(cos2)

[1] 1
[1] -1


#### tan() – Tangent of an angle


In [ ]:
# Example 1: Tangent of 0
tan1 <- tan(0)
print(tan1)

# Example 2: Tangent of pi/4 (should be 1)
tan2 <- tan(pi/4)
print(tan2)

[1] 0
[1] 1


#### cor() – Correlation between two numeric vectors


In [ ]:
# Example 1: Correlation of two simple vectors
cor1 <- cor(c(1, 2, 3), c(4, 5, 6))
print(cor1)

# Example 2: Correlation from a data frame
df_cor <- data.frame(x = 1:5, y = c(2, 4, 6, 8, 10))
cor2 <- cor(df_cor$x, df_cor$y)
print(cor2)

[1] 1
[1] 1


#### cov() – Covariance between two vectors


In [ ]:
# Example 1: Covariance of two vectors
cov1 <- cov(c(1, 2, 3), c(4, 5, 6))
print(cov1)

# Example 2: Covariance from a data frame
cov2 <- cov(df_cor$x, df_cor$y)
print(cov2)

[1] 1
[1] 5



# Data Manipulation



#### data.frame() – Create a data frame

In [ ]:
# Example 1: Create a simple data frame
df1 <- data.frame(Name = c("Alice", "Bob"), Age = c(25, 30))
print(df1)

# Example 2: Create a data frame with different types
df2 <- data.frame(ID = 1:3, Score = c(90, 85, 88), Passed = c(TRUE, TRUE, FALSE))
print(df2)

   Name Age
1 Alice  25
2   Bob  30
  ID Score Passed
1  1    90   TRUE
2  2    85   TRUE
3  3    88  FALSE


#### list() – Create a list (a container for different objects)


In [ ]:
# Example 1: Create a list with mixed types
my_list1 <- list(num = 1, word = "hello", flag = TRUE)
print(my_list1)

# Example 2: Create a nested list
my_list2 <- list(a = 1:3, b = list(inner = c("x", "y")))
print(my_list2)

$num
[1] 1

$word
[1] "hello"

$flag
[1] TRUE

$a
[1] 1 2 3

$b
$b$inner
[1] "x" "y"




#### matrix() – Create a matrix from a vector


In [ ]:
# Example 1: Create a 3x3 matrix
mat1 <- matrix(1:9, nrow = 3, ncol = 3)
print(mat1)

# Example 2: Create a matrix by filling by row
mat2 <- matrix(1:9, nrow = 3, byrow = TRUE)
print(mat2)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


#### array() – Create an array (multi-dimensional)


In [ ]:
# Example 1: Create a 3D array (2x2x3)
arr1 <- array(1:12, dim = c(2, 2, 3))
print(arr1)

# Example 2: Create a 2D array (same as a matrix)
arr2 <- array(1:6, dim = c(2, 3))
print(arr2)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


#### t() – Transpose a matrix (flip rows and columns)


In [ ]:
# Example 1: Transpose a simple matrix
mat3 <- matrix(1:6, nrow = 2)
t_mat3 <- t(mat3)
print(t_mat3)

# Example 2: Transpose a data frame converted to a matrix
df_mat <- data.frame(A = 1:3, B = 4:6)
t_df <- t(as.matrix(df_mat))
print(t_df)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
  [,1] [,2] [,3]
A    1    2    3
B    4    5    6


#### rbind() – Row bind (stack rows together)


In [ ]:
# Example 1: Combine two vectors as rows
row1 <- c(1, 2, 3)
row2 <- c(4, 5, 6)
rbind1 <- rbind(row1, row2)
print(rbind1)

# Example 2: Row bind two data frames with the same columns
df_a <- data.frame(Name = c("Tom"), Age = 20)
df_b <- data.frame(Name = c("Jerry"), Age = 22)
rbind2 <- rbind(df_a, df_b)
print(rbind2)

     [,1] [,2] [,3]
row1    1    2    3
row2    4    5    6
   Name Age
1   Tom  20
2 Jerry  22


#### cbind() – Column bind (attach columns side by side)


In [ ]:
# Example 1: Combine two vectors as columns
col1 <- c(1, 2, 3)
col2 <- c(4, 5, 6)
cbind1 <- cbind(col1, col2)
print(cbind1)

# Example 2: Column bind two data frames (they must have the same number of rows)
df_c <- data.frame(A = 1:3)
df_d <- data.frame(B = 4:6)
cbind2 <- cbind(df_c, df_d)
print(cbind2)

     col1 col2
[1,]    1    4
[2,]    2    5
[3,]    3    6
  A B
1 1 4
2 2 5
3 3 6


#### dim() – Get dimensions of a matrix or data frame


In [ ]:
# Example 1: Get dimensions of a matrix
dim1 <- dim(mat1)
print(dim1)

# Example 2: Get dimensions of a data frame
dim2 <- dim(df1)
print(dim2)

[1] 3 3
[1] 2 2


#### nrow() – Number of rows


In [ ]:
# Example 1: Number of rows in a data frame
nrow1 <- nrow(df1)
print(nrow1)

# Example 2: Number of rows in a matrix
nrow2 <- nrow(mat1)
print(nrow2)

[1] 2
[1] 3


#### ncol() – Number of columns


In [ ]:
# Example 1: Number of columns in a data frame
ncol1 <- ncol(df1)
print(ncol1)

# Example 2: Number of columns in a matrix
ncol2 <- ncol(mat1)
print(ncol2)

[1] 2
[1] 3


#### names() – Get or set names of a vector or list


In [ ]:
# Example 1: Get names from a data frame
names1 <- names(df1)
print(names1)

# Example 2: Set names of a vector
vec_named <- c(10, 20, 30)
names(vec_named) <- c("first", "second", "third")
print(vec_named)

[1] "Name" "Age" 
 first second  third 
    10     20     30 


#### colnames() – Get or set column names of a matrix/data frame


In [ ]:
# Example 1: Get column names of a data frame
cols1 <- colnames(df2)
print(cols1)

# Example 2: Set column names of a matrix
mat4 <- matrix(1:4, nrow = 2)
colnames(mat4) <- c("Col1", "Col2")
print(mat4)

[1] "ID"     "Score"  "Passed"
     Col1 Col2
[1,]    1    3
[2,]    2    4


#### rownames() – Get or set row names of a matrix/data frame


In [ ]:
# Example 1: Get row names of a data frame
rows1 <- rownames(df1)
print(rows1)

# Example 2: Set row names of a matrix
rownames(mat4) <- c("Row1", "Row2")
print(mat4)

[1] "1" "2"
     Col1 Col2
Row1    1    3
Row2    2    4


#### subset() – Select part of data based on conditions


In [ ]:
# Example 1: Subset rows where Age > 25
subset1 <- subset(df2, Score > 85)
print(subset1)

# Example 2: Subset specific columns
subset2 <- subset(df2, select = c(ID, Passed))
print(subset2)

  ID Score Passed
1  1    90   TRUE
3  3    88  FALSE
  ID Passed
1  1   TRUE
2  2   TRUE
3  3  FALSE


#### merge() – Merge two data frames by a common column


In [ ]:
# Example 1: Merge on a common key
df_left <- data.frame(ID = 1:3, Name = c("A", "B", "C"))
df_right <- data.frame(ID = c(2, 3, 4), Score = c(90, 85, 88))
merge1 <- merge(df_left, df_right, by = "ID")
print(merge1)

# Example 2: Merge with all rows kept (full outer join)
merge2 <- merge(df_left, df_right, by = "ID", all = TRUE)
print(merge2)

  ID Name Score
1  2    B    90
2  3    C    85
  ID Name Score
1  1    A    NA
2  2    B    90
3  3    C    85
4  4 <NA>    88


#### apply() – Apply a function over rows or columns of a matrix


In [ ]:
# Example 1: Sum each row of a matrix
apply1 <- apply(mat1, 1, sum)
print(apply1)

# Example 2: Mean of each column
apply2 <- apply(mat1, 2, mean)
print(apply2)

[1] 12 15 18
[1] 2 5 8


#### lapply() – Apply a function to each element of a list, returning a list


In [ ]:
# Example 1: Get the length of each element in a list
lapply1 <- lapply(list("apple", "banana", "cherry"), nchar)
print(lapply1)

# Example 2: Square each number in a list
lapply2 <- lapply(list(1, 2, 3), function(x) x^2)
print(lapply2)

[[1]]
[1] 5

[[2]]
[1] 6

[[3]]
[1] 6

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9



#### sapply() – Like lapply but try to simplify the result


In [ ]:
# Example 1: Get string lengths for a list of words
sapply1 <- sapply(c("apple", "banana", "cherry"), nchar)
print(sapply1)

# Example 2: Square numbers in a vector
sapply2 <- sapply(c(1, 2, 3), function(x) x^2)
print(sapply2)

 apple banana cherry 
     5      6      6 
[1] 1 4 9


#### tapply() – Apply a function over subsets of a vector


In [ ]:
# Example 1: Calculate mean by group
group <- c("A", "B", "A", "B")
values <- c(10, 20, 30, 40)
tapply1 <- tapply(values, group, mean)
print(tapply1)

# Example 2: Sum by group
tapply2 <- tapply(values, group, sum)
print(tapply2)

 A  B 
20 30 
 A  B 
40 60 


#### aggregate() – Aggregate data by groups


In [ ]:
# Example 1: Aggregate sum by group
agg1 <- aggregate(values, by = list(group), FUN = sum)
print(agg1)

# Example 2: Aggregate mean by group
agg2 <- aggregate(values, by = list(group), FUN = mean)
print(agg2)

#### split() – Split data into groups


In [ ]:
# Example 1: Split a vector by a factor
split1 <- split(c(1, 2, 3, 4), group)
print(split1)

# Example 2: Split a data frame by a column
split2 <- split(df2, df2$Passed)
print(split2)

$A
[1] 1 3

$B
[1] 2 4

$`FALSE`
  ID Score Passed
3  3    88  FALSE

$`TRUE`
  ID Score Passed
1  1    90   TRUE
2  2    85   TRUE



#### stack() – Stack data frame columns into key-value pairs


In [ ]:
# Example 1: Stack a data frame
stack1 <- stack(df1)
print(stack1)

# Example 2: Stack a different data frame
stack2 <- stack(df2)
print(stack2)

  values  ind
1  Alice Name
2    Bob Name
3     25  Age
4     30  Age
  values    ind
1      1     ID
2      2     ID
3      3     ID
4     90  Score
5     85  Score
6     88  Score
7      1 Passed
8      1 Passed
9      0 Passed


#### unstack() – Reverse of stack (spread key-value pairs back to columns)


In [ ]:
# Example 1: Unstack the previous stacked data frame
unstack1 <- unstack(stack1)
print(unstack1)

# Example 2: Unstack a different stacked data frame
unstack2 <- unstack(stack2)
print(unstack2)

   Name Age
1 Alice  25
2   Bob  30
  ID Score Passed
1  1    90      1
2  2    85      1
3  3    88      0


#### reshape() – Reshape data between wide and long formats


In [ ]:
# Example 1: Reshape wide to long
df_wide <- data.frame(id = 1:2, time1 = c(10, 20), time2 = c(30, 40))
df_long <- reshape(df_wide, varying = c("time1", "time2"),
                   v.names = "score", timevar = "time",
                   times = c(1, 2), direction = "long")
print(df_long)

# Example 2: Reshape long back to wide
df_wide2 <- reshape(df_long, idvar = "id", timevar = "time", direction = "wide")
print(df_wide2)

    id time score
1.1  1    1    10
2.1  2    1    20
1.2  1    2    30
2.2  2    2    40
    id score.1 score.2
1.1  1      10      30
2.1  2      20      40



# Control Flow & Programming


#### ifelse() – Vectorized if-else (works on each element)


In [ ]:
# Example 1: Check if numbers are even or odd
result1 <- ifelse(c(1, 2, 3, 4) %% 2 == 0, "even", "odd")
print(result1)

# Example 2: Mark values above 5 as "high", others "low"
result2 <- ifelse(c(3, 6, 9), "high", "low")
print(result2)

[1] "odd"  "even" "odd"  "even"
[1] "high" "high" "high"


#### if ... else – Conditional statements


In [ ]:
# Example 1: Simple if-else statement
x <- 10
if (x > 5) {
  print("x is greater than 5")
} else {
  print("x is not greater than 5")
}

# Example 2: Using if-else inside a function
check_number <- function(num) {
  if (num < 0) {
    return("Negative")
  } else {
    return("Non-negative")
  }
}
print(check_number(-3))
print(check_number(4))

[1] "x is greater than 5"
[1] "Negative"
[1] "Non-negative"


#### for – Loop over a sequence


In [ ]:
# Example 1: Print numbers 1 to 5
for (i in 1:5) {
  print(i)
}

# Example 2: Loop over elements in a vector
vec_loop <- c("a", "b", "c")
for (letter in vec_loop) {
  print(letter)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] "a"
[1] "b"
[1] "c"


#### while – Loop while condition is true


In [ ]:
# Example 1: Count from 1 until 5
counter <- 1
while (counter <= 5) {
  print(counter)
  counter <- counter + 1
}

# Example 2: Decrease a value until it is less than 0
val <- 3
while (val >= 0) {
  print(val)
  val <- val - 1
}


[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 3
[1] 2
[1] 1
[1] 0


#### repeat – Loop indefinitely until a break is encountered


In [ ]:
# Example 1: Use repeat loop to count until 3
count <- 1
repeat {
  print(count)
  count <- count + 1
  if (count > 3) break
}

# Example 2: Another repeat example with a condition
i <- 10
repeat {
  i <- i - 2
  print(i)
  if (i <= 4) break
}

[1] 1
[1] 2
[1] 3
[1] 8
[1] 6
[1] 4


#### break – Exit a loop immediately


In [ ]:
# Example: Use break inside a for loop when condition met
for (i in 1:10) {
  if (i == 6) {
    break  # exit loop when i is 6
  }
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


#### next – Skip to next iteration in a loop


In [ ]:
# Example: Skip printing the number 3 in a loop
for (i in 1:5) {
  if (i == 3) {
    next  # skip the rest of this loop cycle
  }
  print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5


#### function() – Define a function


In [ ]:
# Example 1: A simple function that adds two numbers
add_two <- function(a, b) {
  return(a + b)
}
print(add_two(3, 5))

# Example 2: Function with a default parameter
greet <- function(name = "friend") {
  paste("Hello", name)
}
print(greet("Alice"))
print(greet())

[1] 8
[1] "Hello Alice"
[1] "Hello friend"


#### return() – Return a value from a function


In [ ]:
# Example 1: A simple function that adds two numbers
add_two <- function(a, b) {
  return(a + b)
}
print(add_two(3, 5))

# Example 2: Function with a default parameter
greet <- function(name = "friend") {
  paste("Hello", name)
}
print(greet("Alice"))
print(greet())

# (Used above in the add_two and greet functions)

[1] 8
[1] "Hello Alice"
[1] "Hello friend"


#### stop() – Stop execution and throw an error


In [ ]:
# Example 1: Stop if an invalid condition is met inside a function
check_positive <- function(x) {
  if (x < 0) {
    stop("x must be non-negative!")
  }
  return(x)
}
# Uncomment the following line to see the error:
# check_positive(-5)

# Example 2: Stop execution manually
# Uncomment the next line to stop the script:
# stop("Manual stop here!")

#### warning() – Show a warning message without stopping execution


In [ ]:
# Example 1: Issue a warning if a value is too high
warn_if_high <- function(x) {
  if (x > 100) {
    warning("x is very high!")
  }
  return(x)
}
print(warn_if_high(150))
print(warn_if_high(50))

Warning message in warn_if_high(150):
“x is very high!”


[1] 150
[1] 50


#### try() – Try an expression and catch errors quietly


In [ ]:
# Example 1: Try to take the square root of a negative number
result_try1 <- try(sqrt(-1))
print(result_try1)

# Example 2: Try reading a non-existent variable
result_try2 <- try(print(nonexistent_variable))
print(result_try2)

Warning message in sqrt(-1):
“NaNs produced”


[1] NaN
Error in eval(expr, envir) : object 'nonexistent_variable' not found
[1] "Error in eval(expr, envir) : object 'nonexistent_variable' not found\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in eval(expr, envir): object 'nonexistent_variable' not found>


#### tryCatch() – Advanced error handling


In [ ]:
# Example 1: Use tryCatch to handle an error
result_tc <- tryCatch({
  log("a")  # will cause an error
}, error = function(e) {
  "An error occurred"
})
print(result_tc)

# Example 2: tryCatch with finally block
result_tc2 <- tryCatch({
  stop("Oops!")
}, error = function(e) {
  "Caught the error"
}, finally = {
  cat("This is the cleanup code.\n")
})
print(result_tc2)

[1] "An error occurred"
This is the cleanup code.
[1] "Caught the error"



#  Working with Files


#### getwd() – Get current working directory


In [ ]:
# Example 1: Simply print the working directory
wd1 <- getwd()
print(wd1)

# Example 2: Save and print working directory from a variable
wd2 <- getwd()
cat("Working directory is:", wd2, "\n")

[1] "/content"
Working directory is: /content 


#### setwd() – Set the working directory


In [ ]:
# (Be careful with this! It changes your folder for reading/writing files.)
# Example 1: Change to a temporary directory (this should work safely)
# setwd(tempdir())
# cat("Now in temporary directory:", getwd(), "\n")

# Example 2: Set back to original (if you saved it before)
# original_wd <- "your/original/path"  # replace with your actual path
# setwd(original_wd)

#### list.files() – List files in a directory


In [ ]:
# Example 1: List files in current directory
files1 <- list.files()
print(files1)

# Example 2: List files with a specific pattern (e.g., files ending with .R)
files2 <- list.files(pattern = "\\.R$")
print(files2)

[1] "sample_data"
character(0)


#### file.exists() – Check if a file exists


In [ ]:
# Example 1: Check for a file named "test.txt"
exists1 <- file.exists("test.txt")
print(exists1)

# Example 2: Check multiple files at once
exists2 <- file.exists(c("test.txt", "nonexistent.txt"))
print(exists2)

[1] FALSE
[1] FALSE FALSE


#### file.remove() – Delete a file


In [ ]:
# Example 1: Create and then remove a temporary file
temp_file <- tempfile(fileext = ".txt")
cat("Temporary content", file = temp_file)
removed1 <- file.remove(temp_file)
print(removed1)

# Example 2: Try removing a file that likely does not exist
removed2 <- file.remove("no_file.txt")
print(removed2)

[1] TRUE


Warning message in file.remove("no_file.txt"):
“cannot remove file 'no_file.txt', reason 'No such file or directory'”


[1] FALSE


#### read.csv() – Read a CSV file


In [ ]:
# Example 1: Write a small CSV and read it back
df_sample <- data.frame(Name = c("A", "B"), Value = c(10, 20))
temp_csv <- tempfile(fileext = ".csv")
write.csv(df_sample, temp_csv, row.names = FALSE)
df_read1 <- read.csv(temp_csv)
print(df_read1)

# Example 2: Read CSV with header (default behavior)
df_read2 <- read.csv(temp_csv, header = TRUE)
print(df_read2)

  Name Value
1    A    10
2    B    20
  Name Value
1    A    10
2    B    20


#### write.csv() – Write data to a CSV file


In [ ]:
# Example 1: Write a data frame to CSV
write.csv(df_sample, "sample_output.csv", row.names = TRUE)
# Check if file exists afterward
print(file.exists("sample_output.csv"))

# Example 2: Write CSV without row names
write.csv(df_sample, "sample_output2.csv", row.names = FALSE)
print(file.exists("sample_output2.csv"))

[1] TRUE
[1] TRUE


#### read.table() – Read tabular data from a file


In [ ]:
# Example 1: Create a text file and read it as table
temp_txt <- tempfile(fileext = ".txt")
write("1 2 3\n4 5 6", file = temp_txt)
table1 <- read.table(temp_txt)
print(table1)

# Example 2: Read table with a specified separator (space here)
table2 <- read.table(temp_txt, sep = " ")
print(table2)

  V1 V2 V3
1  1  2  3
2  4  5  6
  V1 V2 V3
1  1  2  3
2  4  5  6


#### write.table() – Write data to a file in table format


In [ ]:
# Example 1: Write a data frame to a text file
write.table(df_sample, "sample_table.txt")
print(file.exists("sample_table.txt"))

# Example 2: Write table with row names disabled
write.table(df_sample, "sample_table2.txt", row.names = FALSE)
print(file.exists("sample_table2.txt"))

[1] TRUE
[1] TRUE


#### saveRDS() – Save a single R object to a file


In [ ]:
# Example 1: Save a data frame as an RDS file
saveRDS(df_sample, "sample_data.rds")
print(file.exists("sample_data.rds"))

# Example 2: Save a vector as an RDS file
saveRDS(c(1,2,3), "sample_vector.rds")
print(file.exists("sample_vector.rds"))

[1] TRUE
[1] TRUE


#### readRDS() – Read a single R object from an RDS file


In [ ]:
# Example 1: Read the previously saved data frame
df_from_rds <- readRDS("sample_data.rds")
print(df_from_rds)

# Example 2: Read the vector from the RDS file
vec_from_rds <- readRDS("sample_vector.rds")
print(vec_from_rds)

  Name Value
1    A    10
2    B    20
[1] 1 2 3



# Working with Factors


#### factor() – Create a factor variable


In [1]:
# Example 1: Convert a character vector to a factor
fact_a <- factor(c("low", "medium", "high", "medium"))
print(fact_a)



[1] low    medium high   medium
Levels: high low medium


#### levels() – Get or set levels of a factor


In [ ]:
# Example 1: Get levels of a factor
levels_a <- levels(fact_a)
print(levels_a)

# Example 2: Change levels of a factor
levels(fact_a) <- c("L", "M", "H")
print(fact_a)

[1] "high"   "low"    "medium"
[1] M H L H
Levels: L M H


#### relevel() – Change the reference level of a factor


In [ ]:
# Example 1: Make "blue" the reference level
fact_c <- factor(c("red", "blue", "red", "green"))
fact_c <- relevel(fact_c, ref = "blue")
print(fact_c)

# Example 2: Relevel with a different reference
fact_d <- factor(c("A", "B", "C", "A"))
fact_d <- relevel(fact_d, ref = "C")
print(fact_d)

[1] red   blue  red   green
Levels: blue green red
[1] A B C A
Levels: C A B


#### cut() – Divide numeric data into intervals (factors)


In [ ]:
# Example 1: Cut numbers into equal-width bins
nums <- c(1, 3, 5, 7, 9)
cut1 <- cut(nums, breaks = 3)
print(cut1)

# Example 2: Cut with custom labels
cut2 <- cut(nums, breaks = c(0, 4, 8, 10), labels = c("low", "medium", "high"))
print(cut2)

[1] (0.992,3.67] (0.992,3.67] (3.67,6.33]  (6.33,9.01]  (6.33,9.01] 
Levels: (0.992,3.67] (3.67,6.33] (6.33,9.01]
[1] low    low    medium medium high  
Levels: low medium high



# Date & Time Handling


#### as.POSIXct() – Convert string to date-time (POSIXct)


In [2]:
# Example 1: Convert a date-time string
dt1 <- as.POSIXct("2025-02-03 12:34:56")
print(dt1)



[1] "2025-02-03 12:34:56 UTC"


#### as.POSIXlt() – Convert string to list-like date-time (POSIXlt)


In [3]:
# Example 1: Convert and see the list components
dt_lt1 <- as.POSIXlt("2025-02-03 12:34:56")
print(dt_lt1)



[1] "2025-02-03 12:34:56 UTC"


#### difftime() – Compute the difference between two date-time values


In [4]:
# Example 1: Difference between two dates
diff1 <- difftime(as.Date("2025-02-10"), as.Date("2025-02-03"))
print(diff1)



Time difference of 7 days


#### format() – Format date-time objects as strings


In [5]:
# Example 1: Format a date in a simple way
fmt1 <- format(as.Date("2025-02-03"), "%B %d, %Y")
print(fmt1)



[1] "February 03, 2025"



# Debugging & Environment Management


#### ls() – List objects in the environment


In [6]:
# Example 1: List all current objects
objs1 <- ls()
print(objs1)



[1] "diff1"  "dt_lt1" "dt1"    "fact_a" "fmt1"  


#### rm() – Remove objects from the environment


In [7]:
# Example 1: Remove a single variable
temp_var <- 123
print(temp_var)
rm(temp_var)
# Uncommenting the next line would cause an error since temp_var is removed:
# print(temp_var)


[1] 123


#### gc() – Run garbage collection (free up memory)


In [8]:
# Example 1: Run garbage collection and print result
gc_result1 <- gc()
print(gc_result1)



          used (Mb) gc trigger (Mb) max used (Mb)
Ncells  656448 35.1    1437941 76.8  1437941 76.8
Vcells 1225887  9.4    8388608 64.0  1956779 15.0


#### debug() – Turn on debugging for a function


In [ ]:
# Example 1: Define a simple function and set debug on it
test_fun <- function(x) {
  y <- x + 1
  return(y)
}
debug(test_fun)
# Uncomment the next line to step through the function:
# test_fun(5)
undebug(test_fun)  # Turn off debugging

#### traceback() – Show the call stack after an error


In [9]:
# Example 1: Force an error then show traceback
error_fun <- function() {
  stop("This is an error!")
}

#### print() – Print output to the console


In [ ]:
# Example 1: Print a number
print(100)

# Example 2: Print a message
print("Hello, world!")

# Extra example: Print a vector
print(c("a", "b", "c"))

[1] 100
[1] "Hello, world!"
[1] "a" "b" "c"


#### cat() – Concatenate and print text (no quotes)


In [ ]:
# Example 1: Concatenate and print a simple message
cat("This is a simple message.\n")

# Example 2: Concatenate multiple pieces of text
cat("The answer is", 42, "\n")
# Extra example: Print without automatic newlines (you add \n manually)
cat("Line one.\nLine two.\n")

This is a simple message.
The answer is 42 
Line one.
Line two.
